version: '3.8'

services:
  postgres:
    image: postgres:14
    restart: always
    container_name: nest_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employee_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
